export const allowedBlocks = [
  // motion
  "motion_changexby",
  "motion_changeyby",
  "motion_direction",
  "motion_glidesecstoxy",
  "motion_glideto",
  "motion_goto",
  "motion_gotoxy",
  "motion_ifonedgebounce",
  "motion_movesteps",
  "motion_pointindirection",
  "motion_pointtowards",
  "motion_setrotationstyle",
  "motion_setx",
  "motion_sety",
  "motion_turnleft",
  "motion_turnright",
  "motion_xposition",
  "motion_yposition",

  // looks
  "looks_backdropnumbername",
  "looks_changeeffectby",
  "looks_changesizeby",
  "looks_cleargraphiceffects",
  "looks_costumenumbername",
  "looks_goforwardbackwardlayers",
  "looks_gotofrontback",
  "looks_hide",
  "looks_nextbackdrop",
  "looks_nextcostume",
  "looks_say",
  "looks_sayforsecs",
  "looks_seteffectto",
  "looks_setsizeto",
  "looks_show",
  "looks_size",
  "looks_switchbackdropto",
  "looks_switchbackdroptoandwait",
  "looks_switchcostumeto",
  "looks_think",
  "looks_thinkforsecs",

  // sound
  "sound_changeeffectby",
  "sound_changevolumeby",
  "sound_cleareffects",
  "sound_play",
  "sound_playuntildone",
  "sound_seteffectto",
  "sound_setvolumeto",
  "sound_stopallsounds",
  "sound_volume",

  // events
  "event_broadcast",
  "event_broadcastandwait",
  "event_whenbackdropswitchesto",
  "event_whenbroadcastreceived",
  "event_whenflagclicked",
  "event_whengreaterthan",
  "event_whenkeypressed",
  "event_whenstageclicked",
  "event_whenthisspriteclicked",

  // control
  "control_create_clone_of",
  "control_delete_this_clone",
  "control_forever",
  "control_if",
  "control_if_else",
  "control_repeat",
  "control_repeat_until",
  "control_start_as_clone",
  "control_stop",
  "control_wait",
  "control_wait_until",

  // sensing
  "sensing_answer",
  "sensing_askandwait",
  "sensing_coloristouchingcolor",
  "sensing_current",
  "sensing_dayssince2000",
  "sensing_distanceto",
  "sensing_keypressed",
  "sensing_loudness",
  "sensing_mousedown",
  "sensing_mousex",
  "sensing_mousey",
  "sensing_of",
  "sensing_online",
  "sensing_resettimer",
  "sensing_setdragmode",
  "sensing_timer",
  "sensing_touchingcolor",
  "sensing_touchingobject",
  "sensing_username",

  // operators
  "operator_add",
  "operator_and",
  "operator_contains",
  "operator_divide",
  "operator_equals",
  "operator_gt",
  "operator_join",
  "operator_length",
  "operator_letter_of",
  "operator_lt",
  "operator_mathop",
  "operator_mod",
  "operator_multiply",
  "operator_not",
  "operator_or",
  "operator_random",
  "operator_round",
  "operator_subtract",

  // data
  "variable",
  "list",
  "data_addtolist",
  "data_changevariableby",
  "data_deletealloflist",
  "data_deleteoflist",
  "data_hidelist",
  "data_hidevariable",
  "data_insertatlist",
  "data_itemnumoflist",
  "data_itemoflist",
  "data_lengthoflist",
  "data_listcontainsitem",
  "data_replaceitemoflist",
  "data_setvariableto",
  "data_showlist",
  "data_showvariable",

  // my blocks
  "argument_reporter_boolean",
  "argument_reporter_string_number",
  "procedures_call",
  "procedures_definition",
  // "procedures_prototype",

  // music
  "music_changeTempo",
  "music_getTempo",
  "music_playDrumForBeats",
  "music_playNoteForBeats",
  "music_restForBeats",
  "music_setInstrument",
  "music_setTempo",

  // pen
  "pen_changePenColorParamBy",
  "pen_changePenSizeBy",
  "pen_clear",
  "pen_penDown",
  "pen_penUp",
  "pen_setPenColorParamTo",
  "pen_setPenColorToColor",
  "pen_setPenSizeTo",
  "pen_stamp",

  // video sensing
  "videoSensing_setVideoTransparency",
  "videoSensing_videoOn",
  "videoSensing_videoToggle",
  "videoSensing_whenMotionGreaterThan",/*

  // face sensing
  "faceSensing_faceIsDetected",
  "faceSensing_faceSize",
  "faceSensing_faceTilt",
  "faceSensing_goToPart",
  "faceSensing_pointInFaceTiltDirection",
  "faceSensing_setSizeToFaceSize",
  "faceSensing_whenFaceDetected",
  "faceSensing_whenSpriteTouchesPart",
  "faceSensing_whenTilted",*/

  // text to speech
  "text2speech_setLanguage",
  "text2speech_setVoice",
  "text2speech_speakAndWait",

  // translate
  "translate_getTranslate",
  "translate_getViewerLanguage",/*

  // makey makey
  "makeymakey_whenCodePressed",
  "makeymakey_whenMakeyKeyPressed",

  // micro:bit
  "microbit_displayClear",
  "microbit_displaySymbol",
  "microbit_displayText",
  "microbit_getTiltAngle",
  "microbit_isButtonPressed",
  "microbit_isTilted",
  "microbit_whenButtonPressed",
  "microbit_whenGesture",
  "microbit_whenPinConnected",
  "microbit_whenTilted",

  // lego ev3
  "ev3_beep",
  "ev3_buttonPressed",
  "ev3_getBrightness",
  "ev3_getDistance",
  "ev3_getMotorPosition",
  "ev3_motorSetPower",
  "ev3_motorTurnClockwise",
  "ev3_motorTurnCounterClockwise",
  "ev3_whenBrightnessLessThan",
  "ev3_whenButtonPressed",
  "ev3_whenDistanceLessThan",

  // boost
  "boost_getMotorPosition",
  "boost_getTiltAngle",
  "boost_motorOff",
  "boost_motorOn",
  "boost_motorOnFor",
  "boost_motorOnForRotation",
  "boost_seeingColor",
  "boost_setLightHue",
  "boost_setMotorDirection",
  "boost_setMotorPower",
  "boost_whenColor",
  "boost_whenTilted",

  // weDo 2.0
  "wedo2_getDistance",
  "wedo2_getTiltAngle",
  "wedo2_isTilted",
  "wedo2_motorOff",
  "wedo2_motorOn",
  "wedo2_motorOnFor",
  "wedo2_setLightHue",
  "wedo2_setMotorDirection",
  "wedo2_startMotorPower",
  "wedo2_whenDistance",
  "wedo2_whenTilted",

  // force and acceleration
  "gdxfor_getAcceleration",
  "gdxfor_getForce",
  "gdxfor_getSpinSpeed",
  "gdxfor_getTilt",
  "gdxfor_isFreeFalling",
  "gdxfor_isTilted",
  "gdxfor_whenForcePushedOrPulled",
  "gdxfor_whenGesture",
  "gdxfor_whenTilted",

  /*

  // hacked (functional)
  "control_for_each",
  "control_incr_counter",
  "control_get_counter",
  "control_clear_counter",
  "control_while",
  "sensing_loud",
  "pen_setPenHueToNumber",
  "pen_setPenShadeToNumber",
  "pen_changePenHueBy",
  "pen_changePenShadeBy",

  // hacked (useless)
  "motion_align_scene",
  "motion_scroll_right",
  "motion_scroll_up",
  "motion_xscroll",
  "motion_yscroll",
  "looks_changestretchby",
  "looks_hideallsprites",
  "looks_setstretchto",
  "control_all_at_once",
  "sensing_userid",
  "music_midiSetInstrument",
  "music_midiPlayDrumForBeats",

  // menus
  "motion_glideto_menu",
  "motion_goto_menu",
  "motion_pointtowards_menu",
  "looks_backdrops",
  "looks_costume",
  "sound_sounds_menu",
  "control_create_clone_of_menu",
  "sensing_keyoptions",
  "sensing_distancetomenu",
  "sensing_of_object_menu",
  "sensing_touchingobjectmenu",
  "music_menu_DRUM",
  "music_menu_INSTRUMENT",
  "note",
  "pen_menu_colorParam",
  "videoSensing_menu_ATTRIBUTE",
  "videoSensing_menu_SUBJECT",
  "videoSensing_menu_VIDEO_STATE",
  "text2speech_menu_languages",
  "text2speech_menu_voices",
  "translate_menu_languages",
  "makeymakey_menu_KEY",
  "makeymakey_menu_SEQUENCE",
  "microbit_menu_buttons",
  "microbit_menu_gestures",
  "microbit_menu_tiltDirection",
  "microbit_menu_tiltDirectionAny",
  "microbit_menu_touchPins",
  "matrix",
  "ev3_menu_motorPorts",
  "ev3_menu_sensorPorts",
  "boost_menu_COLOR",
  "boost_menu_MOTOR_DIRECTION",
  "boost_menu_MOTOR_ID",
  "boost_menu_MOTOR_REPORTER_ID",
  "boost_menu_TILT_DIRECTION",
  "boost_menu_TILT_DIRECTION_ANY",
  "wedo2_menu_MOTOR_DIRECTION",
  "wedo2_menu_MOTOR_ID",
  "wedo2_menu_OP",
  "wedo2_menu_TILT_DIRECTION",
  "wedo2_menu_TILT_DIRECTION_ANY",
  "gdxfor_menu_axisOptions",
  "gdxfor_menu_gestureOptions",
  "gdxfor_menu_pushPullOptions",
  "gdxfor_menu_tiltAnyOptions",
  "gdxfor_menu_tiltOptions"

  */
];
